name: campus_calendar  # Project name (must be lowercase with underscores)
description: A campus calendar app built with Flutter.
publish_to: 'none'  # Prevents accidental publishing to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'  # Ensures compatibility with Dart 3

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0  
 
  path_provider: ^2.1.2
  flutter_local_notifications: ^16.3.0  
  table_calendar: ^3.2.0
  shared_preferences: ^2.5.2
  intl: ^0.20.2
  uuid: ^4.5.1
  mailer: ^6.4.1
  image_picker: ^1.1.2
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png  # ✅ Added logo image for Welcome Screen
